# site settings
title: Restoring Pride.
subtitle: In ourselves. In our community.
email: chris@restoringpride.org
description: Restoring Pride provides safe, stable, transitional housing to all members of the LGBTQ community who are homeless and suffering from addiction so they can begin anew.
baseurl: "/" # the subpath of your site, e.g. /blog
url: https://restoringpride.org
author: Christopher Wetherington
street_address: 931 Farragut Street NW
city: Washington
state: DC
zip_code: 20011
country: United States of America
phone: (202) 251-6434

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: 
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: https://www.linkedin.com/company/restoring-pride-inc/
  Twitter: 
  Facebook: https://www.facebook.com/RestoringPride/
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
